### ISSUE TITLE
[BUG] Missing process list on NVIDIA 535.98 driver

### ISSUE THREAD

**Issue by yuzhiguo07** [XuehaiPan/nvitop#93] opened 2023-08-21 21:38 UTC
### Required prerequisites

- [X] I have read the documentation <https://nvitop.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
- [x] I have tried the latest version of nvitop in a new isolated virtual environment.

### What version of nvitop are you using?

1.2.0

### Operating system and version

Ubuntu 22

### NVIDIA driver version

 535.98

### NVIDIA-SMI

```text
Mon Aug 21 16:34:25 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.98                 Driver Version: 535.98       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2080 Ti     Off | 00000000:0A:00.0 Off |                  N/A |
| 40%   46C    P8              22W / 250W |      0MiB / 11264MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 2080 Ti     Off | 00000000:0B:00.0 Off |                  N/A |
|100%   69C    P2             249W / 260W |   9875MiB / 11264MiB |    100%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    1   N/A  N/A    755511      C   python                                     9872MiB |
+---------------------------------------------------------------------------------------+
```

### Python environment

3.11.3 (main, Apr 19 2023, 23:54:32) [GCC 11.2.0] linux
nvidia-ml-py==11.525.131
nvitop==1.2.0

### Problem description

there is a program running on GPU, but there is "No running processes found" in nvitop, but it is shown in nvidia-smi.
![image](https://github.com/XuehaiPan/nvitop/assets/29880106/35c731fc-06da-4ca9-882e-4e9eda3d7794)

### Steps to Reproduce

The Python snippets (if any):

```python

```

Command lines:

```bash

```

**Comment by XuehaiPan** [comment] 2023-08-22 11:53
Duplicate of #88. It is already fixed in the main branch.

**Closed by XuehaiPan** 2023-08-22 11:53 UTC
Labels: bug, upstream, pynvml, api
