### ISSUE TITLE
[Feature Request] Refresh rate < 1 sec

### ISSUE THREAD

**Issue by BlueskyFR** [XuehaiPan/nvitop#65] opened 2023-04-06 08:58 UTC
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
- [X] I have tried the latest version of nvitop in a new isolated virtual environment.

### Motivation

I see the current minimum refresh rate is 1 second.
Could it be something like 0.1 sec so that we can get a more accurate overview of what is happening on the GPU?

### Solution

-

### Alternatives

-

### Additional context

-

**Comment by XuehaiPan** [comment] 2023-04-06 09:30
Duplicate of #32, #63.

> Could it be something like 0.1 sec

Hi @BlueskyFR, the latency from the NVML API call is relatively high. I think it's meaningless to support small intervals like 0.1 second. If you want a fine-grained report of resource usage, maybe you should use a profiler instead.

> so that we can get a more accurate overview of what is happening on the GPU?

1. You can select a process and then press the `<Enter>` key. The metrics on the top row will refresh every 1/4 sec.

<p align="center">
  <img width="100%" src="https://user-images.githubusercontent.com/16078332/192108815-37c03705-be44-47d4-9908-6d05175db230.png" alt="Process Metrics Screen">
  <br/>
  Watch metrics for a specific process (shortcut: <kbd>Enter</kbd> / <kbd>Return</kbd>).
</p>

2. Use `nvitop.ResourceMetricCollector`, see [Resource Metric Collector](https://github.com/XuehaiPan/nvitop#resource-metric-collector) for more information.

**Comment by BlueskyFR** [comment] 2023-04-06 10:29
Thanks for your reply.
Why are calls to NVML so slow?

`nvidia-smi` supports a resolution up to a 10ms refresh rate for instance

**Comment by XuehaiPan** [comment] 2023-04-06 10:48
> Why are calls to NVML so slow?

> `nvidia-smi` supports a resolution up to a 10ms refresh rate for instance

@BlueskyFR `nvidia-smi` cannot achieve this.

1. It depends on how many GPU devices are on board.
2. If you do not enable the persistence mode, the `nvidia-smi` command may take seconds (e.g., 3s) to do a single query.

We can "refresh" the "fake" results every 10ms. But the results may be queried seconds ago. They are not accurate.

Here are some benchmark results from my side. You can try [`hyperfine`](https://github.com/sharkdp/hyperfine) on your machine to see the latency.

- Single NVIDIA 3090 GPU on WSL (persistence mode enabled)

```console
$ hyperfine --warmup 50 --runs 200 nvidia-smi
Benchmark 1: nvidia-smi
  Time (mean ± σ):     113.6 ms ±   8.4 ms    [User: 5.3 ms, System: 3.9 ms]
  Range (min … max):    98.4 ms … 141.4 ms    200 runs
```

- 8 x NVIDIA A100 GPU on native Ubuntu (persistence mode enabled)

```console
$ hyperfine --warmup 50 --runs 200 nvidia-smi
Benchmark 1: nvidia-smi
  Time (mean ± σ):      1.920 s ±  0.417 s    [User: 0.007 s, System: 1.298 s]
  Range (min … max):    1.314 s …  4.250 s    200 runs
```

It takes 2 seconds to do a single query. It cannot run under 10ms.

**Comment by BlueskyFR** [comment] 2023-04-06 13:09
> > Why are calls to NVML so slow?
> 
> > `nvidia-smi` supports a resolution up to a 10ms refresh rate for instance
> 
> @BlueskyFR `nvidia-smi` cannot achieve this.
> 
> 1. It depends on how many GPU devices are on board.
> 2. If the persistence mode is disabled, the `nvidia-smi` command will take more time (up to seconds (e.g., 3s)) to do a single query.
> 
> We can "refresh" the "fake" results every 10ms. But the results may be queried seconds ago. They are not accurate.
> 
> Here are some benchmark results from my side. You can try [`hyperfine`](https://github.com/sharkdp/hyperfine) on your machine to see the latency.
> 
> * Single NVIDIA 3090 GPU on WSL (persistence mode enabled)
> 
> ```
> $ hyperfine --warmup 50 --runs 200 nvidia-smi
> Benchmark 1: nvidia-smi
>   Time (mean ± σ):     113.6 ms ±   8.4 ms    [User: 5.3 ms, System: 3.9 ms]
>   Range (min … max):    98.4 ms … 141.4 ms    200 runs
> ```
> 
> * 8 x NVIDIA A100 GPU on native Ubuntu (persistence mode enabled)
> 
> ```
> $ hyperfine --warmup 50 --runs 200 nvidia-smi
> Benchmark 1: nvidia-smi
>   Time (mean ± σ):      1.920 s ±  0.417 s    [User: 0.007 s, System: 1.298 s]
>   Range (min … max):    1.314 s …  4.250 s    200 runs
> ```
> 
> It takes 2 seconds to do a single query. It cannot run under 10ms.

You are maybe using it wrong 😊

You can see my post here for more details -> https://github.com/influxdata/telegraf/issues/8534#issue-761112264

**Comment by BlueskyFR** [comment] 2023-04-06 13:57
So I think maybe it is more a design problem?
Maybe the same quantity of information cannot be achieved with nvidia-smi but I doubt it

**Closed** 2023-04-07 09:22 UTC
Labels: enhancement

**Comment by BlueskyFR** [comment] 2023-04-13 15:58
Could be a solution, what profiler do you have in mind for instance?

**Comment by XuehaiPan** [comment] 2023-04-14 04:20
> Could be a solution, what profiler do you have in mind for instance?

@BlueskyFR That depends on your use case because profilers need an in-process injection to add hooks to record kernel times. This may need users to update their code. If you are using PyTorch, you may try [`torch.profiler.profile`](https://pytorch.org/tutorials/recipes/recipes/profiler_recipe.html) ([pytorch/kineto](https://github.com/pytorch/kineto)). It can collect fine-grained metrics and also come with a web-based GUI integration. You may also try the [NVIDIA Nsight Systems](https://developer.nvidia.com/nsight-systems), a profiling tool from NVIDIA.
