### ISSUE TITLE
[Question] ERROR: Failed to initialize `curses` (setupterm: could not find terminfo database)

### ISSUE THREAD

**Issue by yyfcc17** [XuehaiPan/nvitop#118] opened 2024-01-01 14:29 UTC
### Required prerequisites

- [X] I have read the documentation <https://nvitop.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
- [X] I have tried the latest version of nvitop in a new isolated virtual environment.

### Questions

after i run nvitop, i got this error

i think this issue is related to miniconda env, i encountered this error twice.

1. i packed my miniconda env, and transfered to another computer to unpack and recreate the env, it is on the second computer, i had this issue.

2. i changed my miniconda path, then i got this issue, before this operation, nvitop runs perfectly.

it is easy to reproduce, you can investigate into it.

thanks for creating this greate tool.

**Comment by XuehaiPan** [comment] 2024-01-01 14:51
Duplicate of #38.

> transfered to another computer

@yyfcc17 Do you set the `TERM` environment variable properly in your shell environment? You can try:

```bash
export TERM="xterm-256color"
export TERMINFO="${CONDA_PREFIX}/share/terminfo"
nvitop
```

**Comment by yyfcc17** [comment] 2024-01-02 12:28
> i think this issue is related to miniconda env, i encountered this error twice.
> 
> 1. i packed my miniconda env, and transfered to another computer to unpack and recreate the env, it is on the second computer, i had this issue.
> 2. i changed my miniconda path, then i got this issue, before this operation, nvitop runs perfectly.
> 


``` shell
export TERM="xterm-256color"
export TERMINFO="${CONDA_PREFIX}/share/terminfo"
nvitop
```

this can solve the first situation, but still not working for the second. 

and i think it is not the reason for this issue, because i have installed nvitop in another env in miniconda, in this env, nvitop works well.

i think maybe the `move operation / change dir operation` breaks the link to terminfo or something like that.

**Comment by yyfcc17** [comment] 2024-01-02 12:34
issue solved.

the conda `ncurses` package is broken, need to reinstall.

for my case:

```shell
rm -rf miniconda3/pkgs/ncurses-6.4-h6a678d5_0
conda install -c conda-forge ncurses
```

then nvitop works again.

**Closed** 2024-01-02 12:35 UTC
Labels: question, cli / gui

**Comment by lhyscau** [comment] 2024-03-05 15:08
> Duplicate of #38.
> 
> > transfered to another computer
> 
> @yyfcc17 Do you set the `TERM` environment variable properly in your shell environment? You can try:
> 
> ```shell
> export TERM="xterm-256color"
> export TERMINFO="${CONDA_PREFIX}/share/terminfo"
> nvitop
> ```

WTF! It works! Thanks!
